FROM node:20-alpine AS base
WORKDIR /app
COPY package*.json ./

FROM base AS deps
RUN npm ci 
# npm ci uses own package-lock.json to install exact versions, so we can be sure that the same versions are installed in both stages (deps and production)

FROM deps AS build
COPY . .
RUN npm run build

FROM node:20-alpine AS production
WORKDIR /app
ENV NODE_ENV=production

COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=build /app/dist ./dist

COPY scripts/validate-env.sh ./scripts/validate-env.sh
RUN chmod +x scripts/validate-env.sh

EXPOSE 3000

USER node
CMD ["sh", "-c", "./scripts/validate-env.sh && npm run migration:run:prod && exec node dist/src/main.js"]
