import { MigrationInterface, QueryRunner } from "typeorm";

export class Auto1783234395048 implements MigrationInterface {
    name = 'Auto1783234395048'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_refresh_tokens_user"`);
        await queryRunner.query(`ALTER TABLE "document_lock_resolutions" DROP CONSTRAINT "FK_document_lock_resolutions_lock"`);
        await queryRunner.query(`ALTER TABLE "document_lock_resolutions" DROP CONSTRAINT "FK_document_lock_resolutions_recipient"`);
        await queryRunner.query(`ALTER TABLE "document_locks" DROP CONSTRAINT "FK_document_locks_document"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_documents_owner"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_documents_parent"`);
        await queryRunner.query(`ALTER TABLE "document_signing_events" DROP CONSTRAINT "FK_document_signing_events_document"`);
        await queryRunner.query(`ALTER TABLE "document_signing_events" DROP CONSTRAINT "FK_document_signing_events_recipient"`);
        await queryRunner.query(`ALTER TABLE "document_signed_artifacts" DROP CONSTRAINT "FK_document_signed_artifacts_document"`);
        await queryRunner.query(`ALTER TABLE "document_signed_artifacts" DROP CONSTRAINT "FK_document_signed_artifacts_recipient"`);
        await queryRunner.query(`ALTER TABLE "document_signed_artifacts" DROP CONSTRAINT "FK_previous_artifact"`);
        await queryRunner.query(`ALTER TABLE "document_recipients" DROP CONSTRAINT "FK_document_recipients_document"`);
        await queryRunner.query(`ALTER TABLE "document_recipients" DROP CONSTRAINT "FK_document_recipients_user"`);
        await queryRunner.query(`ALTER TABLE "public_link_sessions" DROP CONSTRAINT "FK_public_link_sessions_recipient"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP CONSTRAINT "FK_contacts_owner"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP CONSTRAINT "FK_contacts_contact_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_refresh_tokens_token_hash"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_refresh_tokens_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_document_lock_resolutions_lock_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_document_lock_resolutions_recipient_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_document_locks_document_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_documents_owner_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_documents_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_documents_parent_document_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_document_signing_events_document_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_document_signing_events_recipient_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_document_signing_events_occurred_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_document_signed_artifacts_document_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_document_signed_artifacts_recipient_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_document_recipients_document_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_document_recipients_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_document_recipients_signing_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_document_recipients_public_link_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_public_link_sessions_recipient_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_public_link_sessions_expires_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_otp_challenges_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_otp_challenges_resource_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_otp_challenges_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_otp_challenges_scope"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_otp_challenges_scope_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_contacts_owner_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_contacts_contact_user_id"`);
        await queryRunner.query(`ALTER TABLE "document_lock_resolutions" DROP CONSTRAINT "UQ_document_lock_resolutions_lock_recipient"`);
        await queryRunner.query(`ALTER TABLE "document_signed_artifacts" DROP CONSTRAINT "UQ_document_signed_artifacts_doc_recipient"`);
        await queryRunner.query(`ALTER TABLE "document_recipients" DROP CONSTRAINT "UQ_document_recipients_doc_email"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP CONSTRAINT "UQ_contacts_owner_email"`);
        await queryRunner.query(`ALTER TABLE "document_signed_artifacts" ADD CONSTRAINT "UQ_049ca9b5e698ff23dd5450a284c" UNIQUE ("recipient_id")`);
        await queryRunner.query(`ALTER TABLE "document_signed_artifacts" ALTER COLUMN "public_key_hex" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "public_link_sessions" DROP CONSTRAINT "UQ_public_link_sessions_session_hash"`);
        await queryRunner.query(`ALTER TABLE "otp_challenges" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "otp_challenges" ADD "user_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "otp_challenges" DROP COLUMN "otp_hash"`);
        await queryRunner.query(`ALTER TABLE "otp_challenges" ADD "otp_hash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "otp_challenges" DROP COLUMN "otp_salt"`);
        await queryRunner.query(`ALTER TABLE "otp_challenges" ADD "otp_salt" character varying NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_4963e70f10544a3f03f6718f20" ON "document_lock_resolutions" ("lock_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_777b7676861950d6bb313b6e8e" ON "document_lock_resolutions" ("recipient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f6912515086dfd9bdbb6e104cd" ON "document_locks" ("document_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_888a4852e27627d1ebd8a094e9" ON "documents" ("owner_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_709389d904fa03bdf5ec84998d" ON "documents" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_559ed3f74a52a56b5cc181aa79" ON "documents" ("parent_document_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_96cfaed06bb442ce838962a782" ON "document_signing_events" ("document_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_db8a7e4ac2170992055c67c7a0" ON "document_signing_events" ("recipient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3226757ee0e9077cecb47408a0" ON "document_signing_events" ("occurred_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_6ba0fe61d8e09ab758bf69cbf7" ON "document_signed_artifacts" ("document_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_049ca9b5e698ff23dd5450a284" ON "document_signed_artifacts" ("recipient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6cf5a132cb57f7b334e6a8fcdd" ON "document_recipients" ("document_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_83df423228540a6c9bdefcb255" ON "document_recipients" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_38e839011a916195e28ecf84b9" ON "document_recipients" ("signing_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_9c6a8794263f17a9b9c7a89ddc" ON "public_link_sessions" ("recipient_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_abb3dbd46c21142b520e643031" ON "public_link_sessions" ("session_hash") `);
        await queryRunner.query(`CREATE INDEX "IDX_f545cd6907eb43a479893bac0d" ON "public_link_sessions" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_bc8cf2568282e1080164be8fc1" ON "otp_challenges" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e4a38f44c55818f57fd2ffd40e" ON "otp_challenges" ("resource_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bcde3b990304ac5a2c2345ddc6" ON "otp_challenges" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1d2c3c481e5f7bb36152f19958" ON "otp_challenges" ("user_id", "action_type", "resource_type", "resource_id") WHERE status = 'ACTIVE'`);
        await queryRunner.query(`CREATE INDEX "IDX_5a13db35577c3115ef6edf780a" ON "otp_challenges" ("user_id", "action_type", "resource_type", "resource_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ac270d32a01ee22d2e98a8f853" ON "contacts" ("owner_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5c670e5e9eaaf136e7c32c6742" ON "contacts" ("contact_user_id") `);
        await queryRunner.query(`ALTER TABLE "document_lock_resolutions" ADD CONSTRAINT "UQ_ee3f81560414158edb931ca48fa" UNIQUE ("lock_id", "recipient_id")`);
        await queryRunner.query(`ALTER TABLE "document_signed_artifacts" ADD CONSTRAINT "UQ_30cfd7a76b81867ec7c763cefc2" UNIQUE ("document_id", "recipient_id")`);
        await queryRunner.query(`ALTER TABLE "document_recipients" ADD CONSTRAINT "UQ_78bbaefb2d2d1b1dee23a5c71a1" UNIQUE ("document_id", "recipient_email")`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD CONSTRAINT "UQ_c2452640ada6c0a0289003d96db" UNIQUE ("owner_id", "contact_email")`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("patient_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_lock_resolutions" ADD CONSTRAINT "FK_4963e70f10544a3f03f6718f206" FOREIGN KEY ("lock_id") REFERENCES "document_locks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_lock_resolutions" ADD CONSTRAINT "FK_777b7676861950d6bb313b6e8e9" FOREIGN KEY ("recipient_id") REFERENCES "document_recipients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_locks" ADD CONSTRAINT "FK_f6912515086dfd9bdbb6e104cdc" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_888a4852e27627d1ebd8a094e98" FOREIGN KEY ("owner_id") REFERENCES "users"("patient_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_559ed3f74a52a56b5cc181aa792" FOREIGN KEY ("parent_document_id") REFERENCES "documents"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_signing_events" ADD CONSTRAINT "FK_96cfaed06bb442ce838962a7827" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_signing_events" ADD CONSTRAINT "FK_db8a7e4ac2170992055c67c7a0b" FOREIGN KEY ("recipient_id") REFERENCES "document_recipients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_signed_artifacts" ADD CONSTRAINT "FK_6ba0fe61d8e09ab758bf69cbf71" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_signed_artifacts" ADD CONSTRAINT "FK_049ca9b5e698ff23dd5450a284c" FOREIGN KEY ("recipient_id") REFERENCES "document_recipients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_recipients" ADD CONSTRAINT "FK_6cf5a132cb57f7b334e6a8fcdd4" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_recipients" ADD CONSTRAINT "FK_83df423228540a6c9bdefcb255a" FOREIGN KEY ("user_id") REFERENCES "users"("patient_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public_link_sessions" ADD CONSTRAINT "FK_9c6a8794263f17a9b9c7a89ddcb" FOREIGN KEY ("recipient_id") REFERENCES "document_recipients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD CONSTRAINT "FK_ac270d32a01ee22d2e98a8f8532" FOREIGN KEY ("owner_id") REFERENCES "users"("patient_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD CONSTRAINT "FK_5c670e5e9eaaf136e7c32c67422" FOREIGN KEY ("contact_user_id") REFERENCES "users"("patient_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "contacts" DROP CONSTRAINT "FK_5c670e5e9eaaf136e7c32c67422"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP CONSTRAINT "FK_ac270d32a01ee22d2e98a8f8532"`);
        await queryRunner.query(`ALTER TABLE "public_link_sessions" DROP CONSTRAINT "FK_9c6a8794263f17a9b9c7a89ddcb"`);
        await queryRunner.query(`ALTER TABLE "document_recipients" DROP CONSTRAINT "FK_83df423228540a6c9bdefcb255a"`);
        await queryRunner.query(`ALTER TABLE "document_recipients" DROP CONSTRAINT "FK_6cf5a132cb57f7b334e6a8fcdd4"`);
        await queryRunner.query(`ALTER TABLE "document_signed_artifacts" DROP CONSTRAINT "FK_049ca9b5e698ff23dd5450a284c"`);
        await queryRunner.query(`ALTER TABLE "document_signed_artifacts" DROP CONSTRAINT "FK_6ba0fe61d8e09ab758bf69cbf71"`);
        await queryRunner.query(`ALTER TABLE "document_signing_events" DROP CONSTRAINT "FK_db8a7e4ac2170992055c67c7a0b"`);
        await queryRunner.query(`ALTER TABLE "document_signing_events" DROP CONSTRAINT "FK_96cfaed06bb442ce838962a7827"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_559ed3f74a52a56b5cc181aa792"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_888a4852e27627d1ebd8a094e98"`);
        await queryRunner.query(`ALTER TABLE "document_locks" DROP CONSTRAINT "FK_f6912515086dfd9bdbb6e104cdc"`);
        await queryRunner.query(`ALTER TABLE "document_lock_resolutions" DROP CONSTRAINT "FK_777b7676861950d6bb313b6e8e9"`);
        await queryRunner.query(`ALTER TABLE "document_lock_resolutions" DROP CONSTRAINT "FK_4963e70f10544a3f03f6718f206"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP CONSTRAINT "UQ_c2452640ada6c0a0289003d96db"`);
        await queryRunner.query(`ALTER TABLE "document_recipients" DROP CONSTRAINT "UQ_78bbaefb2d2d1b1dee23a5c71a1"`);
        await queryRunner.query(`ALTER TABLE "document_signed_artifacts" DROP CONSTRAINT "UQ_30cfd7a76b81867ec7c763cefc2"`);
        await queryRunner.query(`ALTER TABLE "document_lock_resolutions" DROP CONSTRAINT "UQ_ee3f81560414158edb931ca48fa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c670e5e9eaaf136e7c32c6742"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac270d32a01ee22d2e98a8f853"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5a13db35577c3115ef6edf780a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1d2c3c481e5f7bb36152f19958"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bcde3b990304ac5a2c2345ddc6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e4a38f44c55818f57fd2ffd40e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bc8cf2568282e1080164be8fc1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f545cd6907eb43a479893bac0d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_abb3dbd46c21142b520e643031"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c6a8794263f17a9b9c7a89ddc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38e839011a916195e28ecf84b9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_83df423228540a6c9bdefcb255"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6cf5a132cb57f7b334e6a8fcdd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_049ca9b5e698ff23dd5450a284"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ba0fe61d8e09ab758bf69cbf7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3226757ee0e9077cecb47408a0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_db8a7e4ac2170992055c67c7a0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_96cfaed06bb442ce838962a782"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_559ed3f74a52a56b5cc181aa79"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_709389d904fa03bdf5ec84998d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_888a4852e27627d1ebd8a094e9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f6912515086dfd9bdbb6e104cd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_777b7676861950d6bb313b6e8e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4963e70f10544a3f03f6718f20"`);
        await queryRunner.query(`ALTER TABLE "otp_challenges" DROP COLUMN "otp_salt"`);
        await queryRunner.query(`ALTER TABLE "otp_challenges" ADD "otp_salt" character varying(32) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "otp_challenges" DROP COLUMN "otp_hash"`);
        await queryRunner.query(`ALTER TABLE "otp_challenges" ADD "otp_hash" character varying(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "otp_challenges" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "otp_challenges" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public_link_sessions" ADD CONSTRAINT "UQ_public_link_sessions_session_hash" UNIQUE ("session_hash")`);
        await queryRunner.query(`ALTER TABLE "document_signed_artifacts" ALTER COLUMN "public_key_hex" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "document_signed_artifacts" DROP CONSTRAINT "UQ_049ca9b5e698ff23dd5450a284c"`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD CONSTRAINT "UQ_contacts_owner_email" UNIQUE ("owner_id", "contact_email")`);
        await queryRunner.query(`ALTER TABLE "document_recipients" ADD CONSTRAINT "UQ_document_recipients_doc_email" UNIQUE ("document_id", "recipient_email")`);
        await queryRunner.query(`ALTER TABLE "document_signed_artifacts" ADD CONSTRAINT "UQ_document_signed_artifacts_doc_recipient" UNIQUE ("document_id", "recipient_id")`);
        await queryRunner.query(`ALTER TABLE "document_lock_resolutions" ADD CONSTRAINT "UQ_document_lock_resolutions_lock_recipient" UNIQUE ("lock_id", "recipient_id")`);
        await queryRunner.query(`CREATE INDEX "IDX_contacts_contact_user_id" ON "contacts" ("contact_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_contacts_owner_id" ON "contacts" ("owner_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_otp_challenges_scope_active" ON "otp_challenges" ("user_id", "action_type", "resource_type", "resource_id") WHERE (status = 'ACTIVE'::otp_challenge_status_enum)`);
        await queryRunner.query(`CREATE INDEX "IDX_otp_challenges_scope" ON "otp_challenges" ("user_id", "action_type", "resource_type", "resource_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_otp_challenges_status" ON "otp_challenges" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_otp_challenges_resource_id" ON "otp_challenges" ("resource_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_otp_challenges_user_id" ON "otp_challenges" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_public_link_sessions_expires_at" ON "public_link_sessions" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_public_link_sessions_recipient_id" ON "public_link_sessions" ("recipient_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_document_recipients_public_link_id" ON "document_recipients" ("public_link_id") WHERE (public_link_id IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_document_recipients_signing_status" ON "document_recipients" ("signing_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_document_recipients_user_id" ON "document_recipients" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_document_recipients_document_id" ON "document_recipients" ("document_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_document_signed_artifacts_recipient_id" ON "document_signed_artifacts" ("recipient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_document_signed_artifacts_document_id" ON "document_signed_artifacts" ("document_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_document_signing_events_occurred_at" ON "document_signing_events" ("occurred_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_document_signing_events_recipient_id" ON "document_signing_events" ("recipient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_document_signing_events_document_id" ON "document_signing_events" ("document_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_documents_parent_document_id" ON "documents" ("parent_document_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_documents_status" ON "documents" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_documents_owner_id" ON "documents" ("owner_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_document_locks_document_id" ON "document_locks" ("document_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_document_lock_resolutions_recipient_id" ON "document_lock_resolutions" ("recipient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_document_lock_resolutions_lock_id" ON "document_lock_resolutions" ("lock_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_refresh_tokens_user_id" ON "refresh_tokens" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_refresh_tokens_token_hash" ON "refresh_tokens" ("token_hash") `);
        await queryRunner.query(`ALTER TABLE "contacts" ADD CONSTRAINT "FK_contacts_contact_user" FOREIGN KEY ("contact_user_id") REFERENCES "users"("patient_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD CONSTRAINT "FK_contacts_owner" FOREIGN KEY ("owner_id") REFERENCES "users"("patient_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public_link_sessions" ADD CONSTRAINT "FK_public_link_sessions_recipient" FOREIGN KEY ("recipient_id") REFERENCES "document_recipients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_recipients" ADD CONSTRAINT "FK_document_recipients_user" FOREIGN KEY ("user_id") REFERENCES "users"("patient_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_recipients" ADD CONSTRAINT "FK_document_recipients_document" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_signed_artifacts" ADD CONSTRAINT "FK_previous_artifact" FOREIGN KEY ("previous_artifact_id") REFERENCES "document_signed_artifacts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_signed_artifacts" ADD CONSTRAINT "FK_document_signed_artifacts_recipient" FOREIGN KEY ("recipient_id") REFERENCES "document_recipients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_signed_artifacts" ADD CONSTRAINT "FK_document_signed_artifacts_document" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_signing_events" ADD CONSTRAINT "FK_document_signing_events_recipient" FOREIGN KEY ("recipient_id") REFERENCES "document_recipients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_signing_events" ADD CONSTRAINT "FK_document_signing_events_document" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_documents_parent" FOREIGN KEY ("parent_document_id") REFERENCES "documents"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_documents_owner" FOREIGN KEY ("owner_id") REFERENCES "users"("patient_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_locks" ADD CONSTRAINT "FK_document_locks_document" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_lock_resolutions" ADD CONSTRAINT "FK_document_lock_resolutions_recipient" FOREIGN KEY ("recipient_id") REFERENCES "document_recipients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_lock_resolutions" ADD CONSTRAINT "FK_document_lock_resolutions_lock" FOREIGN KEY ("lock_id") REFERENCES "document_locks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_refresh_tokens_user" FOREIGN KEY ("user_id") REFERENCES "users"("patient_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
